sudo: required

services:
  - docker

before_install:
  - docker build -t flasktest .
script:
 - docker run flasktest python3 test.py

deploy:
  username: ${AZURE_WA_USERNAME}
  provider: azure_web_apps
  password: ${AZURE_WA_PASSWORD}
  site: 'travisflask'
  skip_cleanup: true
  verbose: true  
