sudo: required

services:
  - docker

before_install:
  - docker build -t flasktest .
script:
 - docker run flasktest python3 test.py

deploy:
  AZURE_WA_USERNAME: 'MukundhBhushan'
  provider: azure_web_apps
  AZURE_WA_PASSWORD: 'Nebula@12'
  AZURE_WA_SITE: 'travisflask'
  skip_cleanup: true
  verbose: true  
