sudo: required

services:
  - docker

before_install:
  - docker build -t flasktest .
script:
 - docker run flasktest python3 test.py

deploy:
  username: MukundhBhushan
  provider: azure_web_apps
  password: Nebula@12
  site: 'travisflask'
  skip_cleanup: true
  verbose: true  
