sudo: required

services:
  - docker

before_install:
  - docker build -t flasktest .
script:
 - docker run flasktest python3 test.py

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true  
